### ISSUE TITLE
Fluentd TCP Input not working

### ISSUE THREAD

**Issue by summer0nguyen** [fluent/fluent-logger-php#46]
Hello,
I have plan using Fluentd with PHP 5.6.20 on my system. 
The problem I have is that : PHP use fluent-logger-php but can not push message to FLuentd TCP Input .

Here is my Fluentd Config  : 
\<source>
  @type tcp
  tag tcp.events # required
  format json
  port 20001 # optional. 5170 by default
  bind 0.0.0.0 # optional. 0.0.0.0 by default
  log_level trace
\</source>

\<match **>
  @type stdout

\</match>

And I used the your sample code .

<?php
require_once __DIR__.'/vendor/autoload.php';
use Fluent\Autoloader,
    Fluent\Logger\ConsoleLogger,
    Fluent\Logger\FluentLogger,
    Fluent\Logger\HttpLogger;
$logger = FluentLogger::open("localhost","20001");
/* simple request */
$logger->post("tcp.events",array("hello"=>"world"));

?>

BUT there is nothing in the output  except fluent trace : 

2016-04-14 10:59:32 +0700 [trace]: accepted fluent socket object_id=70064413431380
2016-04-14 10:59:32 +0700 [trace]: closed fluent socket object_id=70064413431380
2016-04-14 10:59:32 +0700 fluent.trace: {"message":"accepted fluent socket object_id=70064413431380"}
2016-04-14 10:59:32 +0700 fluent.trace: {"message":"closed fluent socket object_id=70064413431380"}

Could you please show me how to fix it. 
Thank you very much. 

P.S: It works well with Unix Socket.

**Comment by repeatedly** [comment]
Use `in_forward` plugin, not `in_tcp`. `in_tcp` can't handle client libraries protocol.
I will update the README.

**Comment by summer0nguyen** [comment]
It works . 
I tested with in_tcp a week but can not make it works before asking :) 
btw, Thank you very much.
